# Generated by Django 2.1.3 on 2018-11-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='no_of_students',
            new_name='no_of_seat',
        ),
    ]
