# Generated by Django 2.1.3 on 2018-11-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20181125_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='building_no',
            new_name='building_name',
        ),
    ]
