# Generated by Django 2.1.3 on 2018-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20181125_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='no_of_rooms',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='no_of_seat',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(max_length=200),
        ),
    ]
