# Generated by Django 2.1.3 on 2018-11-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20181125_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='no_of_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
